### ISSUE TITLE
local aggregation

### ISSUE THREAD

**Issue by chyohoo** [guochengqian/PointNeXt#10]
Thanks for sharing your work.
I am confused about the local aggregation module in InvResMLP.  It seems like the Local aggregation is applied on the sampled point set, not the point set before sampling？

**Comment by guochengqian** [comment]
You mean subsampling (downsampling) ? or grouping (neighborhood query)? 
Yes, InvResMLP works on subsampled points after the set abstraction module.

**Comment by chyohoo** [comment]
> 

Thanks for the reply.  Is local aggregation a little bit redundant since the following set abstraction layer also groups features on subsampled points?

**Comment by guochengqian** [comment]
Thank you for your interest. 
Let me ask you. Are all ResBlocks in ResNet redundant?  
InvResMLP is just for making network deeper. check paper for details.
