### ISSUE TITLE
The errors about additive study of data augmentations

### ISSUE THREAD

**Issue by Yuppie898988** [guochengqian/PointNeXt#100]
I notice that there are few mistakes about the improvement of data augmentation in the [paper](https://arxiv.org/abs/2206.04670).

In Sec. 4.4.1 Table 4, the performance is boosted from 77.9% to 81.4% OA in ScanObjectNN, which is +3.5% rather than +2.5%. 

Also, the mIoU in S3DIS area 5 is increased from 59.3% to 61.0% when adopting color auto-contrast (Table 5), which is +1.7% rather than +0.7%.

**Comment by guochengqian** [comment]
@Yuppie898988 thanks for letting us know this! Will correct the paper.
