### ISSUE TITLE
In the implementation of shapenet, is there only poinext-s, no poinext-B, poinext-L implementation code???

### ISSUE THREAD

**Issue by Lizhinwafu** [guochengqian/PointNeXt#101]
In the implementation of ShapeNet , is there only poinext-s, no poinext-B, poinext-L implementation code???

**Comment by yuchenlichuck** [comment]
Hi, there, because of the characteristics of shapenetpart, it is a considerably small dataset and has fewer sampling points in the dataset. In the experiment, we found it is beneficial to use pointnext-s as the backbone and with higher width, the result has got better

**Comment by guochengqian** [comment]
Thanks for your interest. We only trained PointNext-S on ShapeNet
