### ISSUE TITLE
Is RTX2080Ti enough for training?

### ISSUE THREAD

**Issue by BayRanger** [guochengqian/PointNeXt#104]
Hi,
Thank you for your great work. Currently, I've been trying to train the network in ModelNet40 and ShapeNet based on 2080TiGPU, but when using the following command, I guess batch_size =1 works.  `CUDA_VISIBLE_DEVICES=0 python examples/shapenetpart/main.py --cfg cfgs/shapenetpart/pointnext-s.yaml batch_size=1`.
The error is always shown as following
`RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 10.76 GiB total capacity; 33.42 MiB already allocated; 57.94 MiB free; 46.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
Could you provide some hints to solve this issue?

**Comment by yuchenlichuck** [comment]
Hi, there, are both modelnet40 and shapenet out of memory? In the experiment of ShapeNet Part, we train PointNeXt using a batch size of 8 per GPU with 4 V100 GPUs. From my understanding, v100 has ~ 30GiB capacity, so for rtx2080 ti ~10 GiB capacity, it should work out. Can you try to parallel the model with multi gpus?
