### ISSUE TITLE
Question about the sphere sample

### ISSUE THREAD

**Issue by linhaojia13** [guochengqian/PointNeXt#105]
Hi, could you please point me to some references (e.g., paper or blog) on the sphere sampling which is used in `s3dis_sphere.py`? I tried to google it but couldn't find anything about it.

**Comment by linhaojia13** [comment]
@ZhengGongzi Thank you for the reply. I find it hard for me to understand `s3dis_sphere.py`. I would greatly appreciate your help in understanding it! 

First, could you please explain the difference in pre-processing performed by `s3dis.py` and `s3dis_sphere.py`? 
Second, why does Pix4Point not adopt the same data pre-processing as PointNeXt (`s3dis.py`)?"

**Comment by ZhengGongzi** [comment]
@linhaojia13 s3dis_sphere.py involves some not difficult but trivial mechanisms, and it will be more convenient for us to discuss them together through WeChat. I have sent my WeChat account to your email.
