### ISSUE TITLE
数据集ModelNet40

### ISSUE THREAD

**Issue by qqyqq666** [guochengqian/PointNeXt#107]
你好 问下在数据集ModelNet40上的正确率4如何呢

**Comment by yuchenlichuck** [comment]
check  [modelzoo](https://github.com/guochengqian/PointNeXt/blob/master/docs/modelzoo.md)
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ModelNet40 Classificaiton</h3>

name | OA/mAcc (Original) | OA/mAcc (our released) | #params | FLOPs | Throughput (ins./sec.)
-- | -- | -- | -- | -- | --
PointNet++ | 91.9 / - | 93.0 / 90.7 | 1.5M | 1.7G | 1872
PointNeXt-S (C=64) | 93.7±0.3 / 90.9±0.5 | 94.0 / 91.1 | 4.5M | 6.5G | 2033

**Comment by qqyqq666** [comment]
谢谢收到
&nbsp;


许多年以后
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuchen ***@***.***&gt;; 
发送时间: 2023年2月28日(星期二) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [guochengqian/PointNeXt] 数据集ModelNet40 (Issue #107)





 
check  modelzoo
 
ModelNet40 Classificaiton
    name OA/mAcc (Original) OA/mAcc (our released) #params FLOPs Throughput (ins./sec.) 
    PointNet++ 91.9 / - 93.0 / 90.7 1.5M 1.7G 1872 
  PointNeXt-S&nbsp;(C=64) 93.7±0.3 / 90.9±0.5 94.0 / 91.1 4.5M 6.5G 2033
