### ISSUE TITLE
how to  visulize the result of S3DIS 

### ISSUE THREAD

**Issue by TangYuan96** [guochengqian/PointNeXt#117]
how to realize the pic of S3DIS result like the paper

**Comment by guochengqian** [comment]
https://github.com/guochengqian/PointNeXt/blob/master/examples/segmentation/vis_results.py

**Comment by TangYuan96** [comment]
Thanks!

**Comment by gyy520cyaowu** [comment]
> https://github.com/guochengqian/PointNeXt/blob/master/examples/segmentation/vis_results.py

为什么我运行这个代码，就会报错segmentation fault(core dumped)
