### ISSUE TITLE
Where can I find Stanford3dDataset_v1.2?

### ISSUE THREAD

**Issue by EternityDS** [guochengqian/PointNeXt#119]
Hi,

I noticed Pix4Point project uses Stanford3dDataset_v1.2 version of S3DIS which is different from PointNeXt. May I ask where can I get the data of Stanford3dDataset_v1.2? Thank you!

**Comment by mrclovvn** [comment]
Have you figured this out? I have the same issue as you.

**Comment by shayan-nikoo** [comment]
Have you tried [here](https://docs.google.com/forms/d/e/1FAIpQLScDimvNMCGhy_rmBA2gHfDu3naktRm6A8BPwAWWDv-Uhm6Shw/viewform?c=0&w=1)?

**Comment by guochengqian** [comment]
http://buildingparser.stanford.edu/dataset.html#Download
