### ISSUE TITLE
pointops gives error while installing

### ISSUE THREAD

**Issue by smoothumut** [guochengqian/PointNeXt#124]
Hi quochengqian, 

thanks for your great work about openpoints even though I am still in the progress to understand what it actually does : )

Now I am trying to install openpoints but I am having problem with pointops while installing

I do "python setup.py install" on "openpoints/cpp/pointops/" location but it gives error.

in setup.py in pointops folder     

(opt,) = get_config_vars('OPT')
os.environ['OPT'] = " ".join(
    flag for flag in opt.split() if flag != '-Wstrict-prototypes'
)

opt comes null, so that it crashes on split() function. 

I have tried 
(opt,) = get_config_vars()  
but in this case it gives error that "too many values to unpack"

what would be the wrong, I am on windows
thanks thanks in advance

**Comment by zuixiaosanlang** [comment]
meet same question

**Comment by guochengqian** [comment]
sorry. We only support ubuntu. I am not sure about windows.
