### ISSUE TITLE
Install on Mac Silicon

### ISSUE THREAD

**Issue by shayan-nikoo** [guochengqian/PointNeXt#126]
Thanks for your great work.

Is there any chance to install PointNeXt and openpoints as CPU-only on Apple Silicon with M1 Chip (no cuda) only to be able to test one epoch and a very small batch? 

I want to be able to prepare a data loader for my data similar to try S3DIS sem-seg but first I need the code to get working. :)

I tried it but everywhere in the code there are CUDA dependencies. 

The other issue is compiling C++ codes, I tried commenting 'extra_compile_args' to use the native arch64 compiler and then compile them but it doesn't work. Any suggestion on how I can compile the c++ codes on Mac?

**Comment by guochengqian** [comment]
does not support apple. sorry for that.
