### ISSUE TITLE
Can you share the preprocessing steps of ShapeNetPart Dataset?

### ISSUE THREAD

**Issue by AmrinKareem** [guochengqian/PointNeXt#134]
Hi, I have been able to train PointNeXt BasePartSeg model on ShapeNetPart however I would like to extend it to another dataset with a different number of classes and parts. When I run the evaluation, I get poor results. This leads me to believe the datasets have different augmentations and transforms. 

I found the ShapeNetPart dataset from https://drive.google.com/uc?id=1W3SEE-dY1sxvlECcOwWSDYemwHEUbJIS and used it directly to get results. The website no longer has the ShapeNetPart dataset. Can you give me the preprocessing steps of the data in the link, so that I can compare with my dataset?

**Comment by guochengqian** [comment]
I do not think we used any preprocessing. We use the original dataset
