### ISSUE TITLE
Transfer PointNeXt to different problem

### ISSUE THREAD

**Issue by rakomar** [guochengqian/PointNeXt#135]
Hey there, 
I really love the project, thanks!

I want to transfer PointNext or some other model to a different problem, where the task is to classify (or rather detect) a number of specific points in a point cloud. So to say somewhat of a keypoint detection in a point cloud. The dataset is rather small and it might not be as easy to generate new training samples.

I have a couple of questions:

1. What approach do you feel would be most likely to achieve that goal?
a. Transfer learning from the pretrained model for (I guess?) ShapeNetPartSeg?
b. Train a model from scratch?
c. Use a different algorithm family than the point cloud algorithms proposed here (because there might be better algorithms to solve such a problem?)

2. Can I model that problem in your openpoints framework? What I mean is can I create a yaml which will represent that kind of training (as decided in question 1)?

3. And how much benefit can I expect from generating more training samples?

4. To my understanding right now the ShapeNet input data contains of a 7dimensional vector. 3 position, 3 normal and 1...?. Part label? And could this be adapted to be only position and label?

Best regards

**Comment by guochengqian** [comment]
1. you can create more data using public avaiable dataset such as ShapeNetPart and S3DIS. Then transfer to your downstream.
2. yes
3. you have to do your own research
4. yes. play with the code on your self and you will know what to do
