### ISSUE TITLE
Visulize the result of ShapeNetPart dataset?

### ISSUE THREAD

**Issue by coolfeel** [guochengqian/PointNeXt#143]
how to obtain the picture of ShapeNetPart results? Thanks!

**Comment by yuchenlichuck** [comment]
Hi, there thanks for your question~ 😊 Please check the [visualization code](https://github.com/guochengqian/openpoints/blob/f2e73bc3a6a86461dba96b12207501ae3387bac5/dataset/vis3d.py) here
