### ISSUE TITLE
how to use test_s3dis_6fold.py?

### ISSUE THREAD

**Issue by xindeng98** [guochengqian/PointNeXt#17]
I'm sorry, I'm in trouble again and need your help.
the pretrained folders are organized as follows:
![1657336601853](https://user-images.githubusercontent.com/104637328/178089552-46b411ef-ebd0-4a59-a246-ed99291f8e31.png)
and the code like :`CUDA_VISIBLE_DEVICES=1 python examples/segmentation/test_s3dis_6fold.py --cfg cfgs/s3dis/pointvector-l.yaml mode=test wandb.use_wandb=False --pretrained_path log/s3dis/s3dis-train-pointvector-l-ngpus2-seed5494---batch_size-16-20220708-212619-fCRXoWGphDoYQRXD6V6um3`
However, my folder does not have the paragraph named as you show in the readme of test-area5.
![1657336901772](https://user-images.githubusercontent.com/104637328/178089688-68e0c01e-657a-4a53-aae2-3ed0c6e625e4.png)
An error was reported here.
![1657336968252](https://user-images.githubusercontent.com/104637328/178089728-8c5257c8-b0c8-4241-b3b0-0032f30677d7.png)
What do I need to do? Looking forward to your help！

**Comment by guochengqian** [comment]
Pretrained_path should be pointed to a .pth file not a folder

**Comment by xindeng98** [comment]
> Pretrained_path should be pointed to a .pth file not a folder

`CUDA_VISIBLE_DEVICES=1 python examples/segmentation/test_s3dis_6fold.py --cfg cfgs/s3dis/pointvector-l.yaml wandb.use_wandb=False --mode test --pretrained_path /home/dx/PointNeXt-master/log/s3dis/s3dis-train-pointvector-xl-ngpus2-seed2119-20220709-213600-S6xtjwgrjhKXzvdiMiagnH/checkpoint/s3dis-train-pointvector-xl-ngpus2-seed2119-20220709-213600-S6xtjwgrjhKXzvdiMiagnH_ckpt_best.pth`
This problem still occurs. 
![1657427551605](https://user-images.githubusercontent.com/104637328/178131354-869e9b02-9d05-4b6a-ae51-dfcebf948d08.png)
The test command line for testing area 5 is fine, but the test for 6 regions gets an error.

**Comment by xindeng98** [comment]
The cause of the problem I have located is that my folder organization is missing the folder like following:
![image](https://user-images.githubusercontent.com/104637328/178131487-cd05a420-6648-4b3e-80e0-8d50ab420a0b.png)

**Comment by xindeng98** [comment]
I understand that training and validation as well as testing needs to be done on each of the 6 regions. And finally use test_s3dis_6fold.py .

**Comment by guochengqian** [comment]
@

**Comment by mmaaz60** [comment]
Hi @guochengqian,

Is there any detailed instructions provided to train on other areas, like 2 or 3? Thanks

**Comment by linhaojia13** [comment]
@guochengqian Hi, when I trained all the models on each 5-regions, I got mIoU for each fold. I averaged the 6 mIoU results. If I used the averaged results as the 6-fold mIoU, it seems I ignore the points number and classes imbalance among the 6 area. However, I averged the 6 mIoU of each fold  by using your provided pretrained PointNeXt-XL, the results are as following:

**Comment by jc991206** [comment]
> @guochengqian Hi, when I trained all the models on each 5-regions, I got mIoU for each fold. I averaged the 6 mIoU results. If I used the averaged results as the 6-fold mIoU, it seems that I will ignore the imbalance of points number and classes among the 6 area. However, I averged the 6 mIoU of each fold by using your provided pretrained PointNeXt-XL, the results are as following:
> area1 	79.52
> area2 	62.98
> area3 	84.73
> area4 	64.78
> area5 	71.09
> area6 	86.26
> averaged 	74.89
> 
> The averaged result is 74.89, which is consistent with the reported 74.9 in the paper. In summary, I wonder if the two ways of computing 6-fold mIoU metioned aboved will return almost equal results.

May I ask how to run 6-fold cross validation and what is the file directory under pointnext-xl

**Comment by jc991206** [comment]
> > Pretrained_path should be pointed to a .pth file not a folder
> 
> `CUDA_VISIBLE_DEVICES=1 python examples/segmentation/test_s3dis_6fold.py --cfg cfgs/s3dis/pointvector-l.yaml wandb.use_wandb=False --mode test --pretrained_path /home/dx/PointNeXt-master/log/s3dis/s3dis-train-pointvector-xl-ngpus2-seed2119-20220709-213600-S6xtjwgrjhKXzvdiMiagnH/checkpoint/s3dis-train-pointvector-xl-ngpus2-seed2119-20220709-213600-S6xtjwgrjhKXzvdiMiagnH_ckpt_best.pth` This problem still occurs. ![1657427551605](https://user-images.githubusercontent.com/104637328/178131354-869e9b02-9d05-4b6a-ae51-dfcebf948d08.png) The test command line for testing area 5 is fine, but the test for 6 regions gets an error.

May I ask how to run 6-fold cross validation and what is the file directory under pointnext-xl
