### ISSUE TITLE
What is the detailed configuration of the computer please?

### ISSUE THREAD

**Issue by leungMr** [guochengqian/PointNeXt#21]
I used a 3060 12G graphics card, and it reported an error “CUDA out of memory”.
Is it possible to modify the configuration items to make the program run correctly？
![image](https://user-images.githubusercontent.com/37567413/179888946-a4631be3-43df-4ead-8054-1010999151a3.png)

**Comment by leungMr** [comment]
By the way, what is the minimum computer configuration that can support the default running of the program

**Comment by guochengqian** [comment]
What is your command? 
we always use 1 v100 with 32GB

**Comment by leungMr** [comment]
@guochengqian 

`CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/s3dis/pointnext-s.yaml`
`CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/s3dis/pointnext-xl.yaml`

I used the default configuration file and tried the above two commands, and both reported the same error “CUDA out of memory”.
Maybe my computer configuration is too low to study deep learning well?

_hardware：RTX3060 12G、 i7-11700F、 32G_
_software：python7、cuda11.3、 torch1.11、..._


![image](https://user-images.githubusercontent.com/37567413/179922394-af8f6660-0151-4241-a563-40865706beb6.png)

**Comment by guochengqian** [comment]
@leungMr 
i am sorry that you can not run them using the default configuration. You might have to use lower batch size to fit your memory. 
\eg, 
CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/s3dis/pointnext-s.yaml batch_size=8

**Comment by leungMr** [comment]
@guochengqian 

thank you for your prompt reply. According to your suggestion, the program is now running.
thank you very much
