### ISSUE TITLE
S3DIS dataset preprocessing

### ISSUE THREAD

**Issue by lcysonya** [guochengqian/PointNeXt#22]
Hi~ 
I found the S3DIS dataset you provided quite different from the original version. There seems to have a translation in xyz. Is it right? Is there some other processing? Can you describe with more details？

I also notice that you mean to move the scan to coordinate origin by subtracting the minimum.[https://github.com/guochengqian/openpoints/blob/fb998885f2895922ce257affa4eda81ff12a615b/dataset/s3dis/s3dis.py#L97](url)
It quite wired since you already done the same thing in the data preprocessing according to my understanding.

**Comment by lcysonya** [comment]
Thanks a lot. 

There seems to have two official S3DIS dataset, _Stanford3dDataset_v1.2_Aligned_Version_ and _Stanford3dDataset_v1.2_, and stratified transformer use the aligned version while I use the second version.

**Comment by lcysonya** [comment]
The subsampling preprocessing you mentioned above includes 2 steps，1）subsampling with voxel 2) crop certrain number of points with random seed. And I found S3DIS use 24000 points for 2).

Why use voxel_max=24000?  It is for better performance or bigger throughput?  Is it necessary to crop randomly if the scan not as big as s3dis?

**Comment by guochengqian** [comment]
for 2), 24000 points give a decent performance with high training efficiency. 
Randomly cropping gives around 0.2 miou improvement. You can remove randomly cropping if you do not want to use in any case. Code is there, just play around. Have fun. 

Cheers, 
Guocheng

**Comment by lcysonya** [comment]
Thanks！
