### ISSUE TITLE
s3dis

### ISSUE THREAD

**Issue by FT-Zheng** [guochengqian/PointNeXt#24]
Hi, thanks for the nice work! I noticed there is a pointtransformer.py in openpoints/models/backbone. Have you experimented with the performance of pointtransformer under your proposed training strategies? Could you please provide the relevant configuration files (.yaml)?

**Comment by guochengqian** [comment]
the issues with Point Transformer are that we find it is hard for us to reproduce. We are always 2 mIoU lower than it. But no worry, we will continue working on it.
