### ISSUE TITLE
I can't implement the the result of pointneXt-B

### ISSUE THREAD

**Issue by Wen-ZhiCheng** [guochengqian/PointNeXt#29]
Dear Author,
      Thank you for the pointneXt paper, it's very nice.
       But I had implemented the pointneXt-B model, I can't reach the first epoch result.
       My code: [https://github.com/TaylorIn/pointneXt-pytorch](https://github.com/TaylorIn/pointneXt-pytorch)
       I know read source code is very boring, but could you take a look at it sometime?
       Could you give me some advices and measures?
       Thank you very much

**Comment by guochengqian** [comment]
I don't understand your question. I have the PointNeXt-B released.

**Comment by TaylorIn** [comment]
Just for readability of code, I rewrote it with reference to your code.

Sorry, it's my problem.

After S3DIS finished running, I will discuss with you.

Thank you for your attention.
