### ISSUE TITLE
Full scene as input

### ISSUE THREAD

**Issue by HuguesTHOMAS** [guochengqian/PointNeXt#31]
Hi,

I am amazed by your work of great quality. I would like to try your different optimization techniques on KPConv architecture. I only started to look at your code, but I already have one question.

When I read your paper, it seems that you consider loading the entire scene as input as a training augmentation. I am curious if it is really the case, or if it is just at test time that you load the entire scene.

When I look at the default configuration for S3DIS:
https://github.com/guochengqian/PointNeXt/blob/f49f3e6d9b3d9e8cfb353f4ea61502796eba4693/cfgs/s3dis/default.yaml#L10
It seems that for training there is a limit to the input size. Is it right? Have you managed to train with an entire scene of S3DIS as input? I don't see how you could do it without running OOM on your GPUs

Followup question, for the bigger networks like **pointnext-xl**, even a simple inference could lead to OOM errors on a big scene like S3DIS Area_5. Does the inference fit on your GPU or do you have tricks to separate the workload on multiple GPUs?

Best,
Hugues

**Comment by guochengqian** [comment]
Dear @HuguesTHOMAS 
Thank you very much for the encouraging words. Your KPConv is the most influential paper from year 2019 in point cloud domain. 

For your question, we trained all models using one 80G A100. All models should also be able to run in one V100 with 32G mem. I will double check and let you know. 

If it can not feed in one GPU in your case, you should use more GPUs, but keep the total number of batches to be the same as our default in order to reproduce. Failing to do so may make performance around 1 mIoU lower. 

For inference, PointNeXt-XL is runable using only one GTX2080Ti, but just using a smaller val_batch_size. Note batch size does not influence performance in testing. I will write documentation to clarify this point. 

Thanks for your interest, 
let me know if you have further question. 

Best, 
Gordon

**Comment by HuguesTHOMAS** [comment]
Dear Gordon @guochengqian,

Thank you for your kind words, and your detailed answer.

I have another question about your code, I tried to compile your FPS subsampling cuda function located at:
https://github.com/guochengqian/openpoints/tree/410d7dc0f930bc19b9e2f603ac653cbbbe060e0c/cpp/pointnet2_batch

I manage to build the function but I am surprised by how slow it is. In the test I conducted I found the following speeds:

```
Subsampling S3DIS input point cloud spheres initially subsampled a 4cm.
FPS stride = 4
Avg ptcloud size    Avg FPS time    Avg subsample size
     18394            29.109 ms            4598
     30342            73.770 ms            7585
     46334           161.788 ms           11583
     67112           328.652 ms           16777
     88391           559.842 ms           22097
```

It does not seem fast enough to me. For the same amount of points, grid subsampling takes less than 10 ms on CPU and less than 1 ms on GPU.

did you have similar performances or is it faster on your side?

**Comment by guochengqian** [comment]
I would also like to make the point-based methods even faster using Grid sampling. Now our code supports random sampling, but with a cost of performance drop.

**Comment by HuguesTHOMAS** [comment]
> The FPS implementation is from pointnet2 repo.

I know, but it seems to be the one you use in your code. However, you would never have the TP you claim if the speed of FPS was the same as on my computer. Can you share with me the speed of FPS subsampling on your computer?

> Could you locate me to the implementation of your grid_sampling so that we can support them in this repo.

I am currently in the middle of testing subsampling in a new project. I can share my current code with you:
[gpu_subsampling.zip](https://github.com/guochengqian/PointNeXt/files/9454996/gpu_subsampling.zip)
It is inspired by https://github.com/qinzheng93/Easy-KPConv

This works on GPU or CPU

**Comment by guochengqian** [comment]
@HuguesTHOMAS 
Did you profile the speed using the same setting as we mentioned in the paper? `batch_size=16 num_points=15000`. Machine: 32 G V100, 32 CPU cores. 

anyway, I am in the process of releasing ShapeNetPart and ScanNet in my spare time. Meanwhile, I will look into the speed profiling and the grid sampling.

**Comment by guochengqian** [comment]
I will try my best to finish this profiling and update the code in one or two weeks.

**Comment by guochengqian** [comment]
@HuguesTHOMAS  I tested the throughput again. it is consistent with the paper. 

46 instances / second for PointNeXt-XL with input batch_size=16 num_points=15000

```bash
python examples/profile.py --cfg cfgs/s3dis/pointnext-xl.yaml batch_size=16 num_points=15000 timing=True
```
