### ISSUE TITLE
How to reach the mIoU of the released models?

### ISSUE THREAD

**Issue by linhaojia13** [guochengqian/PointNeXt#34]
I train the PointNeXt and ASSANet and find that the results have small or evident gaps with your released models.  Are these results reasonable in my experiments?
Are these gaps due to the randomness? If so, how many trials have you take to reach the mIoU of the released models?

| Model        | My exps | original mIoU | Released mIoU |
|--------------|---------|---------------|---------------|
| PointNeXt-XL | 69.79   | 70.5±0.3      | 71.1          |
| PointNeXt-L  | 68.57   | 69.0±0.5      | 69.3          |
| PointNeXt-B  | 66.60   | 67.3±0.2      | 67.5          |
| PointNeXt-S  | 63.51   | 63.4±0.8      | 64.2          |
| ASSANet      | 64.79   | -             | 65.8          |

**Comment by guochengqian** [comment]
Please refer to the mean value. The released value is the best model of three random runs

**Comment by linhaojia13** [comment]
Thank you very much.
