### ISSUE TITLE
What is the 4-th channel of ScanObjectNN input?

### ISSUE THREAD

**Issue by ZrrSkywalker** [guochengqian/PointNeXt#35]
Thanks for your constructive work!
I noticed that the `in_channels` of `ScanObjectNN` is 4. I wonder what is the 4-th channel?
Prior works only utilize the front 3 channels for training, so is the setting fair?
Thanks!

**Comment by guochengqian** [comment]
height appending as mentioned in the paper

**Comment by ZrrSkywalker** [comment]
Thanks for your quick reply.
