### ISSUE TITLE
Question about the training configuration in classification task

### ISSUE THREAD

**Issue by Silverster98** [guochengqian/PointNeXt#37]
I notice that you use `PointCloudRotation` data transform in the default configuration in scanobjectnn classification task, while your paper claims that random rotation drops the performance. So I am confused about whether you have used random rotation augmentation in your final experiments. Thanks!

https://github.com/guochengqian/PointNeXt/blob/9a45be7d32654eecb3faee0231058bb9a6f5f8e7/cfgs/scanobjectnn/default.yaml#L19

**Comment by guochengqian** [comment]
thanks for letting me know. i will check this out

**Comment by guochengqian** [comment]
Hi @Silverster98  
Note that random rotation works worse in small variants in S3DIS, but works in all other cases.

![image](https://user-images.githubusercontent.com/48788073/191665558-4930176e-117d-41be-9e70-d98d5dbf3d22.png)
