### ISSUE TITLE
What is the difference between class  PointNextDecoder and class  PointNextPartDecoder, and they are used respectively?

### ISSUE THREAD

**Issue by LEONHWH** [guochengqian/PointNeXt#40]
I want to try to build a new network based on PointNext, but found that PointNextPartDecoder needs more parameters, I just want to implement the function of the decoder without implementing the segmentation score.

**Comment by guochengqian** [comment]
it will not use more in the latest version of code. I am merging from PR.

**Comment by guochengqian** [comment]
latest version is available now
