### ISSUE TITLE
CUDA Out of Memory during Inference

### ISSUE THREAD

**Issue by QasimKhan5x** [guochengqian/PointNeXt#41]
I am using the S3DIS dataset the way you have provided. During training, my model runs fine because every sample has maximum 24k points. But during inference, even when batch size is 1, I get CUDA out of memory. My machine is a NVIDIA RTX 3090 that has 24GB memory. Do you think it is possible to do inference with this machine using the entire scene as input? 

Basically, I am training a custom version of DGCNN, which computes nearest neighbors for all the points in the entire scene. During computation of KNN is where I get memory errors. 

Also, if there are any other tips you know that I could use to do inference with the entire scene but avoid memory errors, then please share.

Thank you very much!

**Comment by guochengqian** [comment]
1. a100 with 80G;  2. smaller batch size; 3. entire scene but with smaller number of points
