### ISSUE TITLE
Question about InvResMLP

### ISSUE THREAD

**Issue by liuhui0401** [guochengqian/PointNeXt#44]
I have noticed you set blocks as [1, 1, 1, 1, 1, 1] in ModelNet40 classification task and the '_make_enc' function in PointNextEncoder sets range in (1, blocks). It means there is any InvResMLP in the network, right?

**Comment by guochengqian** [comment]
yes. only segmentation tasks use invresmlp

**Comment by mikkelmedm** [comment]
In the supplementary material you detail InvResMLP are used also in classification tasks?
![image](https://user-images.githubusercontent.com/38498170/195295700-6205e95e-5516-4eb5-aa5a-0e60fbc8387a.png)
