### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by alanWXZ** [guochengqian/PointNeXt#45]
import openpoints.cpp.subsampling.grid_subsampling as cpp_subsampling
ImportError:PointNeXt-master/examples/segmentation/../../openpoints/cpp/subsampling/grid_subsampling.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object

**Comment by guochengqian** [comment]
seems you did not complie the cpp extensions inside openpoints/cpp. please follow install.sh closely
