### ISSUE TITLE
how to implement code in scannetv2 and shapenetpart?

### ISSUE THREAD

**Issue by zouyanmei** [guochengqian/PointNeXt#48]
Hi, thanks for your great work. I have achieved 72.12% mIoU in S3DIS area5 with PointNext-XL as a baseline. So I want to validate my idea in other datasets like ScanNet and ShapeNetPart. Thanks for your sharing, again. Here are my experimental results.
![s3dis_area5](https://user-images.githubusercontent.com/45259702/190884438-dd8ae14f-1f30-42eb-8259-69b4b632ee35.png)

**Comment by guochengqian** [comment]
code is available in PR. I just need to merge

**Comment by zouyanmei** [comment]
> code is available in PR. I just need to merge

Thanks for your reply. If convenient, I hope you can show your detailed results about S3DIS 6 fold. Thanks.

**Comment by guochengqian** [comment]
available now in main
