### ISSUE TITLE
why always show "RuntimeError: CUDA error: out of memory"?

### ISSUE THREAD

**Issue by wang88256187** [guochengqian/PointNeXt#5]
My machine have a 3090 GPU(24GB), and I run the smallest cfg (pointnext-b). It still show :
untimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

**Comment by guochengqian** [comment]
hi @wang88256187 , 
I don't know what happened in your case. Normally, inference can be done with RTX2080TI GPU with 11G memory.
