### ISSUE TITLE
How to reproduce the results you released?

### ISSUE THREAD

**Issue by liuhui0401** [guochengqian/PointNeXt#51]
As for the classification on ModelNet40 and ScanObjectNN, I set the same seed as the logs with the highest results you released. But I can get the same results. For example, for the classification on ScanObjectNN, I can't get the result 88.2(OA). Instead, I got 87.786(OA). Does your stronger data augmentation as you mentioned in the paper help the results promote? Does the code contain the data augmentation? Thanks.

**Comment by guochengqian** [comment]
87.8 is the same as we reported (avg value)
88.2 is the best among three random runs
