### ISSUE TITLE
The latest code still needs some modifications

### ISSUE THREAD

**Issue by zouyanmei** [guochengqian/PointNeXt#52]
thank you for your sharing. But when I try to reproduce classification in ModelNet40. they are ./openpoints/models/layers/__init__.py and ./openpoints/models/layers/group.py.

from .group_embed import SubsampleGroup, PointPatchEmbed

and

class GroupAll(nn.Module):
    def __init__(self, ):
        super().__init__()

    def forward(self, new_xyz: torch.Tensor, xyz: torch.Tensor, features: torc
h.Tensor = None):
        grouped_xyz = xyz.transpose(1, 2).unsqueeze(2)
        if features is not None:
            grouped_features = features.unsqueeze(2)
            return None, grouped_xyz, grouped_features
        else:
            return None, grouped_xyz, None

**Comment by guochengqian** [comment]
dear @zouyanmei 

Thanks for letting me know. i have fixed this issues and reproduces the results at least for classification tasks (scanobjectnn and modelnet).
Please use the latest code

**Comment by guochengqian** [comment]
@yuchenlichuck  Please double check for segmentation tasks (S3DIS, ShapeNetPart, and ScanNet).
