### ISSUE TITLE
data augmentation : Point resample

### ISSUE THREAD

**Issue by jumptiger66** [guochengqian/PointNeXt#56]
Hello,
I want to know where is the code for data augmentation point resample (used in Table 4).
Thanks.

**Comment by guochengqian** [comment]
During testing, an uniform 1024 points are sampled. 
https://github.com/guochengqian/openpoints/blob/41b7693711c3cc78695cef2f0f77d9285e48c73b/dataset/scanobjectnn/scanobjectnn.py#L64

**Comment by jumptiger66** [comment]
Thank u for your reply！
Best regard！
