### ISSUE TITLE
No results in results/scannet/val/pointnext-xl

### ISSUE THREAD

**Issue by zouyanmei** [guochengqian/PointNeXt#61]
Thank you for sharing. 
After running `CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/scannet/pointnext-xl.yaml wandb.use_wandb=False mode=test --pretrained_path log/scannet/scannet-train-pointnext-xl-ngpus2-seed2447-20221012-170603-mV9fBHWwNpVgQ3kazgrWUv/checkpoint/scannet-train-pointnext-xl-ngpus2-seed2447-20221012-170603-mV9fBHWwNpVgQ3kazgrWUv_ckpt_best.pth. `, no files are generated. Is this normal?

**Comment by zouyanmei** [comment]
In addition, I improved on Pointnext and implemented 71.8%mIoU on ScanNet. Is this result reportable? Because I don't think the result is good enough.

**Comment by guochengqian** [comment]
> 

it is normal. log file is generated inside log/scannet/scannet-train-pointnext-xl-ngpus2-seed2447-20221012-170603-mV9fBHWwNpVgQ3kazgrWUv/

**Comment by zouyanmei** [comment]
> 

Thanks a lot.

**Comment by KISEOKJUNG** [comment]
Hi, @zouyanmei 
I have same problem with you, only log file is generated. Could you tell me the path to check results file?
