### ISSUE TITLE
resume proble

### ISSUE THREAD

**Issue by xindeng98** [guochengqian/PointNeXt#62]
![1665982409856](https://user-images.githubusercontent.com/104637328/196092845-e26b29c9-96e6-4882-b43a-e5173c2a9aa9.png)
During my experiments, I found some errors in the resume section of your shapenetpart/main.py, the parameters inside validate_fn function were written in reverse, and the return result should be accepted with three variables instead of two. @guochengqian

**Comment by yuchenlichuck** [comment]
Thank you for your message and help!😊 The resume mode we haven't modified to the latest version. We will update the code to fix the issue!
