### ISSUE TITLE
The number of points in ScanObjectNNHardest

### ISSUE THREAD

**Issue by warriorsniu** [guochengqian/PointNeXt#65]
The paper claims that 1024 points of each instance are used in  ScanObjectNN. However, the default setting in the code is 2048 and it is ignored in the config file. So, I wonder how many points you used for ScanObjectNN. 
![image](https://user-images.githubusercontent.com/58773198/196680182-a22957d7-bfd8-4a8c-bfe6-b636606a02f9.png)
![image](https://user-images.githubusercontent.com/58773198/196680283-635da351-6c9d-4fb3-a657-64012feedd7c.png)

**Comment by yuchenlichuck** [comment]
Hi, there !😊 Thanks for your questions! We use 1024 points for ScanObjectNN. Please Check the Config file of ScanObjectNN and the parameters `num_points` in  [Config](https://github.com/guochengqian/PointNeXt/blob/master/cfgs/scanobjectnn/default.yaml)

```dataset:
  common:
    NAME: ScanObjectNNHardest
    data_dir: './data/ScanObjectNN/h5_files/main_split'
  train:
    split: train
  val:
    split: val
    num_points: 1024 

num_points: 1024  # the number of points passed into model
num_classes: &nclass
  15
```

**Comment by warriorsniu** [comment]
I got it! Thank you!
