### ISSUE TITLE
Training occasionally stops, the GPU utilization is occasionally 0, train on s3dis

### ISSUE THREAD

**Issue by ybc-ybc** [guochengqian/PointNeXt#66]
No matter how I adjust batchsize or change machine, or test on the server. All have this phenomenon.
but the scannet dataset did not appear this phenomenon.

**Comment by Roywangj** [comment]
hi @ybc-ybc , have you finish the problem? I met the same problem, but dont know how to fix it.

**Comment by ybc-ybc** [comment]
It should be caused by data reading and preprocessing, gpu processing is faster than CPU.

**Comment by Roywangj** [comment]
hi @ybc-ybc , do you have any method to solve the problem?

**Comment by ybc-ybc** [comment]
> hi @ybc-ybc , do you have any method to solve the pro

my CPU is i5-12400, GPU is 3090. Maybe a better computer would alleviate the problem

**Comment by Roywangj** [comment]
hi @ybc-ybc , thanks for your reply. It helps a lot.
