### ISSUE TITLE
weird 6-fold results on S3DIS

### ISSUE THREAD

**Issue by linhaojia13** [guochengqian/PointNeXt#68]
I train the models and run the `test_s3dis_6fold.py`, but the results is weird as follows:
| Area | OA    | mACC  | mIoU  | ceiling | floor | wall  | beam  | column | window | door  | chair | table  | bookcase | sofa  | board  | clutter | best_epoch |
|------|-------|-------|-------|---------|-------|-------|-------|--------|--------|-------|-------|--------|----------|-------|--------|---------|------------|
| 1    | 91.40 | 87.09 | 79.51 | 96.34   | 95.99 | 84.12 | 62.25 | 69.13  | 85.78  | 88.89 | 74.32 | 87.54  | 76.95    | 63.26 | 74.96  | 74.07   | 55         |
| 2    | 89.07 | 77.58 | 65.98 | 90.29   | 96.72 | 82.00 | 38.26 | 57.11  | 65.92  | 67.68 | 61.90 | 84.41  | 77.32    | 54.99 | 19.98  | 61.19   | 31         |
| 3    | 93.65 | 92.23 | 84.58 | 96.13   | 98.06 | 88.06 | 74.03 | 66.41  | 90.34  | 91.99 | 75.65 | 85.44  | 89.37    | 76.89 | 89.41  | 77.72   | 38         |
| 4    | 90.70 | 84.60 | 73.24 | 96.33   | 98.08 | 85.83 | 65.04 | 71.99  | 56.39  | 74.51 | 67.02 | 82.00  | 67.49    | 66.31 | 52.96  | 68.19   | 79         |
| 5    | 90.61 | 76.35 | 69.91 | 95.09   | 98.34 | 84.19 | 0.00  | 29.90  | 57.98  | 77.41 | 81.77 | 90.41  | 75.89    | 76.66 | 79.24  | 62.00   | 52         |
| 6    | 93.87 | 91.11 | 85.80 | 96.56   | 97.82 | 89.34 | 83.93 | 80.41  | 85.91  | 91.02 | 78.62 | 89.13  | 91.74    | 77.02 | 78.50  | 75.44   | 42         |
| all  | 87.86 | 90.62 | 81.61 | 97.18   | 97.99 | 93.98 | 94.31 | 100.00 | 100.00 | 97.12 | 13.33 | 100.00 | 100.00   | 0.00  | 100.00 | 66.98   | -          |

the results in area 1~6 seem normal but the summary result in the last row is weird. IoUs of some classes are 0.00 althouth they are non-zero on each area. And what is weirder, IoUs of some classes reach 100%! What's more, all these strange per-class IoUs brings about a very high 6-fold mIoU, 81.61, which is impossible.
Did you meet such problems when run  `test_s3dis_6fold.py` ? @guochengqian

**Comment by linhaojia13** [comment]
https://github.com/guochengqian/PointNeXt/blob/9d5179281169a4d52fe3892986b9ccce156e2805/examples/segmentation/test_s3dis_6fold.py#L34-L35
In Line 34 of `test_s3dis_6fold.py`, it requirs function `test` to return `allarea_cm`.

However, the function `test` return `cm` but not `all_cm` in line 674 of `main.py`.
https://github.com/guochengqian/PointNeXt/blob/9d5179281169a4d52fe3892986b9ccce156e2805/examples/segmentation/main.py#L670-L674

Is this mismatching cause the weird 6-fold results？

**Comment by linhaojia13** [comment]
> https://github.com/guochengqian/PointNeXt/blob/9d5179281169a4d52fe3892986b9ccce156e2805/examples/segmentation/test_s3dis_6fold.py#L34-L35
> 
> In Line 34 of `test_s3dis_6fold.py`, it requirs function `test` to return `allarea_cm`.
> 
> However, the function `test` return `cm` but not `all_cm` in line 674 of `main.py`.
> 
> https://github.com/guochengqian/PointNeXt/blob/9d5179281169a4d52fe3892986b9ccce156e2805/examples/segmentation/main.py#L670-L674
> 
> Is this mismatching cause the weird 6-fold results？

After I revise the codes to make function `test` return `all_cm` and run ` test_s3dis_6fold.py` again, the results are as follows: 

| Area | OA    | mACC  | mIoU  | ceiling | floor | wall  | beam  | column | window | door  | chair | table | bookcase | sofa  | board | clutter | best_epoch |
|------|-------|-------|-------|---------|-------|-------|-------|--------|--------|-------|-------|-------|----------|-------|-------|---------|------------|
| 1    | 91.40 | 87.09 | 79.51 | 96.34   | 95.99 | 84.12 | 62.25 | 69.13  | 85.78  | 88.89 | 74.32 | 87.54 | 76.95    | 63.26 | 74.96 | 74.07   | 55         |
| 2    | 89.07 | 77.58 | 65.98 | 90.29   | 96.72 | 82.00 | 38.26 | 57.11  | 65.92  | 67.68 | 61.90 | 84.41 | 77.32    | 54.99 | 19.98 | 61.19   | 31         |
| 3    | 93.65 | 92.23 | 84.58 | 96.13   | 98.06 | 88.06 | 74.03 | 66.41  | 90.34  | 91.99 | 75.65 | 85.44 | 89.37    | 76.89 | 89.41 | 77.72   | 38         |
| 4    | 90.70 | 84.60 | 73.24 | 96.33   | 98.08 | 85.83 | 65.04 | 71.99  | 56.39  | 74.51 | 67.02 | 82.00 | 67.49    | 66.31 | 52.96 | 68.19   | 79         |
| 5    | 90.61 | 76.35 | 69.91 | 95.09   | 98.34 | 84.19 | 0.00  | 29.90  | 57.98  | 77.41 | 81.77 | 90.41 | 75.89    | 76.66 | 79.24 | 62.00   | 52         |
| 6    | 93.87 | 91.11 | 85.80 | 96.56   | 97.82 | 89.34 | 83.93 | 80.41  | 85.91  | 91.02 | 78.62 | 89.13 | 91.74    | 77.02 | 78.50 | 75.44   | 42         |
| all  | 93.87 | 91.11 | 85.80 | 96.56   | 97.82 | 89.34 | 83.93 | 80.41  | 85.91  | 91.02 | 78.62 | 89.13 | 91.74    | 77.02 | 78.50 | 75.44   | -          |

The 6-folds results in the last row are exactly same with the results of area 6. The 6-fold results are still incorrect but provide some clues. 
I re-examine the meaning of `all_cm` and `cm` in function `test`. I find that `all_cm` maintains the ConfusionMatrix of current area and `cm` just maintains the ConfusionMatrix of current file.
Therefore, it seems that what we need to do is just to add an variable to accumulate the ConfusionMatrix values of all the area that has been evaluated.

**Comment by linhaojia13** [comment]
As mentioned above, I do some revisions on the codes to accumulate the ConfusionMatrix values of all the area that has been evaluated.

First, I replace the null initialization of cfg.allarea_cm with a standard initialization:
```
    # cfg.allarea_cm = None  # using the same cm
    cfg.allarea_cm = ConfusionMatrix(num_classes=cfg.num_classes, ignore_index=cfg.ignore_index)
```
Then, I revise the returns of function `test` from `cm` to `all_cm`:
```
    if label is not None:
        tp, union, count = all_cm.tp, all_cm.union, all_cm.count
        if cfg.distributed:
            dist.all_reduce(tp), dist.all_reduce(union), dist.all_reduce(count)
        miou, macc, oa, ious, accs = get_mious(tp, union, count)
        #return miou, macc, oa, ious, accs, cm
        return miou, macc, oa, ious, accs, all_cm
```
Third, I make the `cfg.allarea_cm` accumulate the `all_cm` which returns from the function `test`:
```
    # test_miou, test_macc, test_oa, test_ious, test_accs, cfg.allarea_cm = test(
    #     model, data_list, cfg, num_votes=1)
    test_miou, test_macc, test_oa, test_ious, test_accs, all_cm = test(
        model, data_list, cfg, num_votes=1)
    cfg.allarea_cm.value += all_cm.value
``` 

After these modifications, I re-run `test_s3dis_6fold.py` and get resonable results. 
@guochengqian Do you think that my modifications are correct?

**Comment by linhaojia13** [comment]
Using the modified `test_s3dis_6fold.py`, I evaulated the PointNeXt-XL with your provided pretrained models. The returned OA, mAcc and mIoU are 90.32, 83.04 and 74.92, which are same with that in the paper. 

| method       | Area | OA    | mACC  | mIoU  | ceiling | floor | wall  | beam  | column | window | door  | chair | table | bookcase | sofa  | board | clutter | best_epoch |
|--------------|------|-------|-------|-------|---------|-------|-------|-------|--------|--------|-------|-------|-------|----------|-------|-------|---------|------------|
| pointnext-xl | 1    | 91.16 | 87.17 | 79.52 | 96.41   | 95.77 | 82.88 | 52.83 | 70.92  | 85.69  | 88.81 | 74.83 | 85.02 | 81.32    | 69.62 | 74.76 | 74.94   | 32         |
| pointnext-xl | 2    | 85.52 | 74.68 | 62.98 | 90.42   | 93.69 | 82.35 | 48.09 | 75.82  | 73.30  | 76.36 | 59.40 | 45.90 | 54.88    | 49.44 | 23.79 | 45.26   | 50         |
| pointnext-xl | 3    | 93.64 | 92.71 | 84.73 | 95.69   | 98.38 | 88.52 | 75.90 | 64.68  | 89.87  | 90.74 | 78.59 | 87.34 | 88.28    | 75.40 | 91.32 | 76.73   | 85         |
| pointnext-xl | 4    | 88.60 | 74.92 | 64.78 | 94.30   | 97.06 | 84.34 | 7.64  | 61.04  | 37.92  | 68.34 | 68.71 | 74.75 | 62.41    | 60.65 | 61.69 | 63.30   | 85         |
| pointnext-xl | 5    | 90.94 | 77.13 | 71.09 | 93.68   | 98.58 | 85.26 | 0.00  | 42.27  | 60.59  | 70.93 | 84.44 | 92.41 | 80.35    | 78.08 | 76.59 | 60.98   | 80         |
| pointnext-xl | 6    | 94.06 | 92.06 | 86.26 | 96.57   | 97.94 | 89.69 | 83.89 | 82.38  | 88.32  | 91.39 | 79.24 | 89.12 | 89.13    | 76.78 | 81.49 | 75.41   | 87         |
| pointnext-xl | all  | 90.32 | 83.04 | 74.92 | 94.13   | 96.81 | 85.04 | 61.44 | 64.18  | 68.48  | 78.67 | 76.90 | 70.18 | 74.33    | 70.73 | 69.87 | 63.16   | -          |

**Comment by guochengqian** [comment]
hi @linhaojia13  Thank you very much for noticing this bug. This might cause because some colleagues change something wrongly when running other experiments. 
Do you get a time to open a PR for this? Thank you very much!!!

**Comment by linhaojia13** [comment]
I haved open a [PR ](https://github.com/guochengqian/PointNeXt/pull/71) for this issue. If there still exists problems, please let me know.

**Comment by guochengqian** [comment]
I am really glad to hear that. Thanks for your contribution and support. I will review your PR later and land it in few days.

**Comment by womeizhaol** [comment]
> I train the models and run the `test_s3dis_6fold.py`, but the results is weird as follows:
> Area 	OA 	mACC 	mIoU 	ceiling 	floor 	wall 	beam 	column 	window 	door 	chair 	table 	bookcase 	sofa 	board 	clutter 	best_epoch
> 1 	91.40 	87.09 	79.51 	96.34 	95.99 	84.12 	62.25 	69.13 	85.78 	88.89 	74.32 	87.54 	76.95 	63.26 	74.96 	74.07 	55
> 2 	89.07 	77.58 	65.98 	90.29 	96.72 	82.00 	38.26 	57.11 	65.92 	67.68 	61.90 	84.41 	77.32 	54.99 	19.98 	61.19 	31
> 3 	93.65 	92.23 	84.58 	96.13 	98.06 	88.06 	74.03 	66.41 	90.34 	91.99 	75.65 	85.44 	89.37 	76.89 	89.41 	77.72 	38
> 4 	90.70 	84.60 	73.24 	96.33 	98.08 	85.83 	65.04 	71.99 	56.39 	74.51 	67.02 	82.00 	67.49 	66.31 	52.96 	68.19 	79
> 5 	90.61 	76.35 	69.91 	95.09 	98.34 	84.19 	0.00 	29.90 	57.98 	77.41 	81.77 	90.41 	75.89 	76.66 	79.24 	62.00 	52
> 6 	93.87 	91.11 	85.80 	96.56 	97.82 	89.34 	83.93 	80.41 	85.91 	91.02 	78.62 	89.13 	91.74 	77.02 	78.50 	75.44 	42
> all 	87.86 	90.62 	81.61 	97.18 	97.99 	93.98 	94.31 	100.00 	100.00 	97.12 	13.33 	100.00 	100.00 	0.00 	100.00 	66.98 	-
> 
> the results in area 1~6 seem normal but the summary result in the last row is weird. IoUs of some classes are 0.00 althouth they are non-zero on each area. And what is weirder, IoUs of some classes reach 100%! What's more, all these strange per-class IoUs brings about a very high 6-fold mIoU, 81.61, which is impossible. Did you meet such problems when run `test_s3dis_6fold.py` ? @guochengqian

May I ask how to run 6-fold cross validation and what is the file directory under pointnext-xl
