### ISSUE TITLE
FLOP count in FPS

### ISSUE THREAD

**Issue by TonyLianLong** [guochengqian/PointNeXt#7]
Does the FLOP count include Furtherest Point Sampling? The FPS algorithm that you use is written in CUDA and I believe DeepSpeed could not infer the FLOPs directly. Is that right?

**Comment by guochengqian** [comment]
no, we do not count. 
When referring to FLOPs, MACs, in the deep learning domain, most people refer to computations in matrix multiplications, and more specifically convolutions layers.
