### ISSUE TITLE
module 不会安装？有什么方法吗？

### ISSUE THREAD

**Issue by 1981672112** [guochengqian/PointNeXt#70]
![2022-10-31 15-28-49 的屏幕截图](https://user-images.githubusercontent.com/85494189/198954517-cff15c2d-a5a6-406d-9266-15ef43647de4.png)

**Comment by zouyanmei** [comment]
不用管，直接跳过就好了。保证你的环境是在cuda11.3以及GCC7.5.0下面配置的就行

**Comment by 1981672112** [comment]
谢谢作者，晚上我查了这个module是动态管理环境的，我自己新建的环境python3.7cuda11.3torch1.12可以运行代码，在跑分类，因为您给的创建环境是在线安装的，那个一般都安装torch超时失败，然后，我看到其他位置会激活使用您给的环境名，这样对自己建的环境影响大吗？有点担心

**Comment by guochengqian** [comment]
@zouyanmei 
thanks for answering the questions. 

@1981672112 
module is only for slurm. just ignore it.
