### ISSUE TITLE
the validation set results and the test set results differ greatly on ScanNet

### ISSUE THREAD

**Issue by zouyanmei** [guochengqian/PointNeXt#74]
I modified PointNeXt and got a 74.0% mIoU result on the ScanNet validation set. But when I submitted the predicted results to ScanNet, I only got a 71.0% mIoU. I think it is unreasonable. So, I would like to know whether there is a way to improve the test performance further, thanks so much. Below are the relative results.
results on validation set:
![validate](https://user-images.githubusercontent.com/45259702/200119342-20723cc8-cca2-4782-be72-1f77553d824d.png)
results on test set:
![test](https://user-images.githubusercontent.com/45259702/200119374-0134c77d-4236-42c3-9c1f-7893154e97ae.png)

**Comment by guochengqian** [comment]
hi @zouyanmei  
Please follow recent works such as Stratified Transformer. They utilize testing voting to improve performance. 

A pr on testing voting is highly appreciated. Thank you!

**Comment by zouyanmei** [comment]
Thank you so much!!!!
