### ISSUE TITLE
The problem of throughput on ShapenetPart

### ISSUE THREAD

**Issue by xindeng98** [guochengqian/PointNeXt#76]
![image](https://user-images.githubusercontent.com/104637328/200252337-7a65af9c-0dee-4386-89b6-4d7c4b44d4a6.png)
This is a big difference compared to the results reported in the paper. I confirm that it is not a problem with the code or machine configuration, because I have no problem testing the throughput on the classification. So I'm wondering if there is a problem with the throughput of the other works in Table3.
![image](https://user-images.githubusercontent.com/104637328/200253068-404cbfef-20ac-4910-985d-a848790f5ef5.png)

**Comment by guochengqian** [comment]
which machine are you using?
the throughput has to be tested on the exact same GPU, CPU, and mem as we have.

**Comment by guochengqian** [comment]
you mentioned you can reproduce classification throughput. OKay, in this case, I will figure this out after CVPR. 
Thank you for letting me know.

**Comment by guochengqian** [comment]
hi @xindeng98 

please note that in the camera ready version, we update the throughput of shapenetpart models, which is close to what you have reported.
Thanks

**Comment by guochengqian** [comment]
![image](https://user-images.githubusercontent.com/48788073/210286751-4f51c854-a0fa-41b5-b1ab-d8421aa92c02.png)
