### ISSUE TITLE
example of semanticKITTI dataset

### ISSUE THREAD

**Issue by dream-toy** [guochengqian/PointNeXt#77]
Hi, @guochengqian:

Thank you for your great work.

Could please give an example of training and testing of the semanticKITTI dataset?

In my implementation, the pointVit takes about 5 hours for testing sequence 08.

Please help.....

**Comment by guochengqian** [comment]
sorry, we currently do not have a plan for this.

**Comment by zouyanmei** [comment]
> Hi, @guochengqian:
> 
> Thank you for your great work.
> 
> Could please give an example of training and testing of the semanticKITTI dataset?
> 
> In my implementation, the pointVit takes about 5 hours for testing sequence 08.
> 
> Please help.....
Hello, I would like to ask you which is the training and testing performance of the semanticKITTI dataset? I have the plan to implement pointnext on semanticKITTI.

**Comment by zouyanmei** [comment]
@dream-toy Hello, I would like to ask you which is the training and testing performance of the semanticKITTI dataset? I have the plan to implement pointnext on semanticKITTI.

**Comment by dream-toy** [comment]
> @dream-toy Hello, I would like to ask you which is the training and testing performance of the semanticKITTI dataset? I have the plan to implement pointnext on semanticKITTI.

Hi, @zouyanmei 
Sorry, due to the long inference time, I do not finish the training and give up this experiment.
