### ISSUE TITLE
how to process the ballquery result 

### ISSUE THREAD

**Issue by lmb633** [guochengqian/PointNeXt#80]
Hi:

In the  /openpoints/models/backbone/pointnextPyG.py, if i use **ballquery**, the result is like [[0, 0, 0, 1, 1],  [0, 1, 2, 3, 4]], the neighbor of each node are not the same.

How can i transfer it to the format of [B,3,N,K],where B(batch size), N(point number),K(k neighbor)

**Comment by guochengqian** [comment]
pointnextPyG is not supported yet. It is still under development and this file is also an outdated version of pointnext.

**Comment by guochengqian** [comment]
We do not have plan for now to support pyg
