### ISSUE TITLE
Quick question about PointNeXt

### ISSUE THREAD

**Issue by SimingYan** [guochengqian/PointNeXt#81]
Hi guocheng,

Thanks for your great work! The codebase is also clean and easy to use. 
May I ask have you tried to use PointNeXt as an encoder backbone for 3d object detection task? According to my understanding, it should also observe the improvement.

**Comment by guochengqian** [comment]
no. i never worked on detection.  
there is another issue asks for the same application. maybe you guys can have a talk. 

https://github.com/guochengqian/PointNeXt/issues/78
