### ISSUE TITLE
Why didn't I generate a predicted point cloud after testing?

### ISSUE THREAD

**Issue by Lizhinwafu** [guochengqian/PointNeXt#82]
Why didn't I generate a predicted point cloud after testing?

**Comment by yuchenlichuck** [comment]
Hi, there thanks for your question~ 😊 Please check the [visualization code](https://github.com/guochengqian/openpoints/blob/f2e73bc3a6a86461dba96b12207501ae3387bac5/dataset/vis3d.py) here

**Comment by yuchenlichuck** [comment]
Hi, I didn't come across this issue before. After I searched for some solutions in StackOverflow and GitHub, I found some possible reasons for this: memory requirement is larger than the limit, so in this case, you may try on GPU with higher memories or reduce the batch size. Please let me know if this can help you or not, and we welcome you to share your solutions on it. Thank you!

**Comment by zouyanmei** [comment]
> ![image](https://user-images.githubusercontent.com/33644565/202661338-0f194cc2-f4e8-425f-9e18-92b7d424c38e.png) What is the reason when I train the s3dis format.


[shapenetpart.zip](https://github.com/guochengqian/PointNeXt/files/10067516/shapenetpart.zip)
This is the visualization code I implemented. Maybe you can refer to it.
