### ISSUE TITLE
Random seed value for Best ScanObjectNN Results

### ISSUE THREAD

**Issue by sheshap** [guochengqian/PointNeXt#83]
Hi Authors/Anyone,

Can you please share the seed value (from the log files) that gave 88.1% (87.7+0.4) accuracy on ScanObjectNN?
We know the seed value is randomly generated, but it is stored in the log file for that run.

It would greatly help in recreating results closer to the claimed ones.

Thank you so much for your attention and participation.

P.S: The best I have created is 87.6% accuracy (seed 7719).

**Comment by zouyanmei** [comment]
> Hi Authors/Anyone,
> 
> Can you please share the seed value (from the log files) that gave 88.1% (87.7+0.4) accuracy on ScanObjectNN? We know the seed value is randomly generated, but it is stored in the log file for that run.
> 
> It would greatly help in recreating results closer to the claimed ones.
> 
> Thank you so much for your attention and participation.
> 
> P.S: The best I have created is 87.6% accuracy (seed 7719).

As mentioned in the pre-trained model, the seed is 6166. You can find it in the pre-trained log file. https://drive.google.com/drive/folders/1A584C9x5uAqppbjNNiVqlA_7uOOOlEII

**Comment by sheshap** [comment]
Thank you so much
