### ISSUE TITLE
I get the following prompt when running

### ISSUE THREAD

**Issue by fgoxiapapopoz** [guochengqian/PointNeXt#84]
Thank you very much for such a good code, but I get the following error during the run of 
Traceback (most recent call last):
  File "examples/classification/train.py", line 6, in <module> 
from openpoints.utils import set_random_seed, save_checkpoint, load_checkpoint, resume_checkpoint, setup_logger_dist, 
ModuleNotFoundError: No module named 'openpoints' 
 Hope to get your help, thank you very much

**Comment by SimonBuusJensen** [comment]
You need to follow the instructions in the install.sh:
```
# download openpoints
git submodule update --init --recursive
git submodule update --remote --merge # update to the latest version
...
```

**Comment by guochengqian** [comment]
@SimonBuusJensen  thanks for the contribution

**Comment by fgoxiapapopoz** [comment]
> 

thanks
