### ISSUE TITLE
Custom dataset regression task + inference on cpu

### ISSUE THREAD

**Issue by mikkelmedm** [guochengqian/PointNeXt#85]
Thanks a lot for your great work!

As stated, I am working on a custom dataset trying to predict angles and translations of planes intersecting input pointclouds, thus it's essentially a regression task of a rotation and a translation matrix.
Currently I am have reconfigured the `modelnet40ply2048/pointnext-s.yaml` classification head to perform regression instead, which works alright. 
However, I am curious if I can perhaps gain more from using feature propagation as well, or if there are better ways of doing regression tasks with PointNeXt? 

Also, would like to inference the model on CPU - so wondering if it would be straight forward to substitute the cpp code with perhaps PointNet++ equivalent code (fps/ball query etc.) to be able to run on CPU?

Kindly,
Mikkel

**Comment by guochengqian** [comment]
if it is node-level regression, you might need feature propagation, otherwise, it should be standard just replacing classification head to regression head using the classification architecture.

For the CPU application, we do not have a plan for it. You have to do you own research.
