### ISSUE TITLE
Why can't git?

### ISSUE THREAD

**Issue by Lizhijian-123** [guochengqian/PointNeXt#86]
Why can't git?
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by yuchenlichuck** [comment]
Hi, there~ please make sure your local git setting is correct, our PointNeXt is public in GitHub, you can just `git clone https://github.com/guochengqian/PointNeXt`. Thank you!

**Comment by Lizhijian-123** [comment]
> Hi, there~ please make sure your local git setting is correct, our PointNeXt is public in GitHub, you can just `git clone https://github.com/guochengqian/PointNeXt`. Thank you!

Thank you for answer,but Why not provide a way to directly download the code and then install it.
Instead, we must use git to download, and then use install.sh to run.maybe sometimes it's not so convenient.Thanks

**Comment by CCInc** [comment]
@Lizhijian-123 you can download a zip file of the code directly from github. https://stackoverflow.com/a/2751270

**Comment by yuchenlichuck** [comment]
@CCInc Thank you for your sharing! @Lizhijian-123 Hope it helps to solve your problem. Check the screenshot and you can download the github repo directly.
<img width="529" alt="image" src="https://user-images.githubusercontent.com/38585175/207041403-d0a1a54c-a404-4d21-95cb-4c27a7b006d9.png">
