### ISSUE TITLE
Will this project run on windows

### ISSUE THREAD

**Issue by leefty-1024** [guochengqian/PointNeXt#88]
When I run it on windows, I run "python setup.py install", an error has occurred. error: command 'cl.exe' failed: No such file or directory

**Comment by liuxinren456852** [comment]
You need to install visual studio build tools

**Comment by guochengqian** [comment]
@liuxinren456852 Thank you for the help.

**Comment by Staubsaugerbeutel** [comment]
> When I run it on windows, I run "python setup.py install", an error has occurred. error: command 'cl.exe' failed: No such file or directory

which setup.py are you referring to? I don't find this in the current version of this project but it would be kind of comfortable to run this on Windows
