### ISSUE TITLE
How to save segmentation results on S3DIS

### ISSUE THREAD

**Issue by shn-hchsk** [guochengqian/PointNeXt#89]
Even if I set visualize=True, the predicted .obj files were not generated but the result folder was generated. 
Could you please tell me how to generate the files?

**Comment by guochengqian** [comment]
hi @shn-hchsk please share your command here.

**Comment by shn-hchsk** [comment]
@guochengqian Thank you for your reply. I found the .obj files were saved in the pre-trained path folder.

**Comment by KISEOKJUNG** [comment]
please let me know the .obj files path and should I change the code in cfg to save the .obj file?
