### ISSUE TITLE
How to train network in other datasets?

### ISSUE THREAD

**Issue by Mr-Sue** [guochengqian/PointNeXt#91]
I have made a dataset, and I want to use the network to get segmentation results.
The format of my dataset is [ x, y, z, label ]. And I have converted to [ x, y, z, 0, 0, 0, label ].
Can you give some instructions on how to train? Thanks!

**Comment by guochengqian** [comment]
check the code S3DIS and ScanNet. you have to write a custom_data.py inside openpoints/dataset following s3dis.py

**Comment by Mr-Sue** [comment]
s3dis.py,s3dis_sphere.py

**Comment by Mr-Sue** [comment]
Thank for your reply!
I am trying to use S3DIS to train my dataset, but I am in trouble.
I tried to cut my dataset into 6 pieces, named like Area_1_..., Area_2_.....
I changed the 'num_classes' and related parameters in s3dis_sphere.py and s3dis.py in /PointNeXt/openpoints/dataset/s3dis.
And I changed 'num_classes' in pointnext-xl.yaml and default.yaml in /PointNeXt/cfgs/s3dis
But, the range of pred data is still from 0 to 12...
============================================================================================
Error in 'class ConfusionMatrix':

        unique_mapping = true.flatten() * self.virtual_num_classes + pred.flatten()
        # print(np.unique(np.array(true.flatten().tolist())))  [0,1,2,3,4,5]
        # print(np.unique(np.array(pred.flatten().tolist()))) [0,1,2,3,4,5,6,7,8,9,10,11,12]
        bins = torch.bincount(unique_mapping, minlength=self.virtual_num_classes**2)
        self.value += bins.view(self.virtual_num_classes, self.virtual_num_classes)[:self.num_classes, :self.num_classes]
============================================================================================
Can you give me a clue！Thanks again.

**Comment by guochengqian** [comment]
he range of pred data depends of the num_classes (categories, like bed, vase,column, book, xxx),  which is not relevant to your data split
