### ISSUE TITLE
how to decide the hyperparameter decay_epochs?

### ISSUE THREAD

**Issue by Daniellli** [guochengqian/PointNeXt#96]
hi,

i found  that the hyperparameter  decay_epochs is specific for different dataset. And, I want to  collect my own dataset  and  train it with such  useful framework,  which let me have to consider  such hyperparameter. 

appreciate for your help.

**Comment by guochengqian** [comment]
use consine decay for your own dataset, it is easier. 
for multistep step, the good start is [0.7 0.9] * max_epochs
