### ISSUE TITLE
How to reproduce the S3DIS 6-Fold results?

### ISSUE THREAD

**Issue by Daniellli** [guochengqian/PointNeXt#97]
hi,  thank you for your such contribution. 
I want to reproduce the S3DIS 6-Fold results in your paper and meet some problem.   could you show me the cross-validation code  or some way to do it (i am not familar with the processed dataset).

**Comment by guochengqian** [comment]
check readme here: https://guochengqian.github.io/PointNeXt/examples/s3dis/
Test on All Areas
CUDA_VISIBLE_DEVICES=0 python examples/segmentation/test_s3dis_6fold.py --cfg cfgs/s3dis/pointnext-xl.yaml mode=test --pretrained_path pretrained/s3dis/pointnext-xl

**Comment by womeizhaol** [comment]
> hi, thank you for your such contribution. I want to reproduce the S3DIS 6-Fold results in your paper and meet some problem. could you show me the cross-validation code or some way to do it (i am not familar with the processed dataset).

May I ask how to run 6-fold cross validation and what is the file directory under pointnext-xl
