### ISSUE TITLE
can you provide the pretrained weight for pix4point? 

### ISSUE THREAD

**Issue by liuyyy111** [guochengqian/PointNeXt#99]
the official mae only provide the base，large and huge model, where can i download the weight mae small model? can you release the mae_s.pth?

**Comment by yuchenlichuck** [comment]
Hi, there, thank you for your attention on pix4point, we will let you know once we update the `mae_s.pth` file. Thank you.

**Comment by guochengqian** [comment]
This work is till in-progress. We will release everything after it gets accepted. Thanks for your attention.
